import webbrowser
import os
import time
webbrowser.open("https://i.imgur.com/GIaPc3o.jpg")
webbrowser.open("https://i.imgur.com/LfGbUL6.jpg")
webbrowser.open("https://i.imgur.com/XWL3r3K.jpg")
webbrowser.open("https://i.imgur.com/uAFOQDh.jpg")
webbrowser.open("https://i.imgur.com/DB094u9.jpg")
webbrowser.open("https://i.imgur.com/LDTr4Ql.jpg")
webbrowser.open("https://i.imgur.com/ibxmTCF.jpg")
webbrowser.open("https://i.imgur.com/c3wLfcu.jpg")
webbrowser.open("https://i.imgur.com/ztN1dQ8.jpg")
webbrowser.open("https://i.imgur.com/JBzLy3Z.jpg")
webbrowser.open("https://i.imgur.com/DhfOVjT.jpg")
webbrowser.open("https://i.imgur.com/DhfOVjT.jpg")
webbrowser.open("https://i.imgur.com/b5B9Zgz.jpg")
webbrowser.open("https://i.imgur.com/C65WADK.jpg")
webbrowser.open("https://i.imgur.com/Uax5QIz.png")
webbrowser.open("https://i.imgur.com/QGch9FC.png")
webbrowser.open("https://i.imgur.com/hG55Vt2.png")
webbrowser.open("https://i.imgur.com/r0o92bB.png")
webbrowser.open("https://i.imgur.com/OlhqhAK.png")
webbrowser.open("https://i.imgur.com/G6I0ClM.png")
webbrowser.open("https://i.imgur.com/UtpDeQM.png")
webbrowser.open("https://i.imgur.com/jxeYeF3.png")
webbrowser.open("https://i.imgur.com/lMEHZmt.png")
webbrowser.open("https://i.imgur.com/6U6CxJK.png")
webbrowser.open("https://i.imgur.com/YLX3AP3.png")
webbrowser.open("https://i.imgur.com/XBVMGIW.png")
webbrowser.open("https://i.imgur.com/Go5oLMn.png")
time.sleep(10)
os.system("taskkill /im firefox.exe /f")