# Generated by Django 2.1.3 on 2018-12-09 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20181202_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fName', models.TextField()),
                ('lName', models.TextField()),
                ('email', models.TextField()),
                ('address', models.TextField()),
                ('address2', models.TextField()),
                ('country', models.TextField()),
                ('state', models.TextField()),
                ('zipCode', models.IntegerField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameOnCard', models.TextField()),
                ('cardNumber', models.IntegerField(max_length=16)),
                ('cardExp', models.TextField(max_length=5)),
                ('cardCVV', models.IntegerField(max_length=3)),
            ],
        ),
    ]
